# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MessageBuffer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MessageBuffer.proto',
  package='',
  serialized_pb=_b('\n\x13MessageBuffer.proto\"\xb8\x01\n\rMessageBuffer\x12\x33\n\x08msg_type\x18\x01 \x02(\x0e\x32\x1b.MessageBuffer.Message_Type:\x04\x45\x43HO\x12\x11\n\tsent_time\x18\x02 \x02(\t\x12\x11\n\tfrom_addr\x18\x03 \x02(\t\x12\x0f\n\x07to_addr\x18\x04 \x02(\t\x12\x0c\n\x04\x64\x61ta\x18\x05 \x01(\t\"-\n\x0cMessage_Type\x12\x08\n\x04\x45\x43HO\x10\x00\x12\t\n\x05PRINT\x10\x01\x12\x08\n\x04TIME\x10\x02')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_MESSAGEBUFFER_MESSAGE_TYPE = _descriptor.EnumDescriptor(
  name='Message_Type',
  full_name='MessageBuffer.Message_Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ECHO', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PRINT', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TIME', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=163,
  serialized_end=208,
)
_sym_db.RegisterEnumDescriptor(_MESSAGEBUFFER_MESSAGE_TYPE)


_MESSAGEBUFFER = _descriptor.Descriptor(
  name='MessageBuffer',
  full_name='MessageBuffer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg_type', full_name='MessageBuffer.msg_type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sent_time', full_name='MessageBuffer.sent_time', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='from_addr', full_name='MessageBuffer.from_addr', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='to_addr', full_name='MessageBuffer.to_addr', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='MessageBuffer.data', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MESSAGEBUFFER_MESSAGE_TYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=208,
)

_MESSAGEBUFFER.fields_by_name['msg_type'].enum_type = _MESSAGEBUFFER_MESSAGE_TYPE
_MESSAGEBUFFER_MESSAGE_TYPE.containing_type = _MESSAGEBUFFER
DESCRIPTOR.message_types_by_name['MessageBuffer'] = _MESSAGEBUFFER

MessageBuffer = _reflection.GeneratedProtocolMessageType('MessageBuffer', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGEBUFFER,
  __module__ = 'MessageBuffer_pb2'
  # @@protoc_insertion_point(class_scope:MessageBuffer)
  ))
_sym_db.RegisterMessage(MessageBuffer)


# @@protoc_insertion_point(module_scope)
